# Name: Eduardo Manuel Costa Moreira
# Student ID: MOR21500097
# Date: 17/01/2024
import base64

# Do not run independently, run this through main.py

# Current plan: Develop this communication app to send in the data inserted from the user and send the
# data to the API to output a desired outcome that's encrypted, the user can decrypt the message if they choose

# This is where imports are handled
import requests
import api_codes
from cryptography.fernet import Fernet


def api_code_fetch(status_code):
    # Uses the status code it gets from the response and fetches the description of the status code
    status_response = str(status_code) + " " + api_codes.api_codes(status_code)
    return status_response


def decryptData():
    user_key = input("Enter the key: ")  # Input the key generated by the API from the JSON
    user_token = input("Enter the token: ")  # Input the token generated by the API from the JSON
    try: # Attempt to put key into Fernet
        data_key = Fernet(user_key)  # Inserts the key into Fernet
        token_decrypted = data_key.decrypt(user_token)  # Decrypts the token using the key
        return token_decrypted
    except: # If the token / key is invalid print to the user that it is invalid
        print("INVALID TOKEN/KEY")
        return "The data could not be decrypted due to a false token / key"


def API(url):
    response = requests.get(url)  # This sends a request and gets a response
    api_status = api_code_fetch(response.status_code)  # This fetches the API status code
    print("It got to this stage before printing")
    print("Status Code: " + api_status)
    data = response.text
    print(data)  # Print the encrypted data
    user_input = input("Would you like to decrypt the data? Y/N: ")
    if user_input == "Y":
        decrypted_message = decryptData()  # Get the decrypted message
        print(decrypted_message)  # Print out the decrypted message
    if user_input == "N":
        print("After this program ends, all information will be forgotten!")
